// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT-cR1y-R3kx-HvU-O-TvicLDPUiempAk',
    appId: '1:857209672432:web:3e40848f38f4ce4c8c6835',
    messagingSenderId: '857209672432',
    projectId: 'fir-appsec2',
    authDomain: 'fir-appsec2.firebaseapp.com',
    storageBucket: 'fir-appsec2.appspot.com',
    measurementId: 'G-ST4W0FWNP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnSERpBTG7g7v2c5xGlUeknDjeDnP3U4Y',
    appId: '1:857209672432:android:bae82d02c781d75e8c6835',
    messagingSenderId: '857209672432',
    projectId: 'fir-appsec2',
    storageBucket: 'fir-appsec2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMc9v7iLg71pkSPYSl4iwcLjSZhup4SD8',
    appId: '1:857209672432:ios:6880278d1b641a598c6835',
    messagingSenderId: '857209672432',
    projectId: 'fir-appsec2',
    storageBucket: 'fir-appsec2.appspot.com',
    iosBundleId: 'com.example.firebaseAppSec2',
  );
}
